server:
  port: 9007
  forward-headers-strategy: native

spring:
  kafka:
    bootstrap-servers: kafka:9092
    streams:
      application-id: notifications-stream
      properties:
        default.key.serde: org.springframework.kafka.support.serializer.JsonSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        partitioner.class: com.ee.notificationmanager.kafka.partitioner.ArchiveEventKafkaPartitioner
    topics:
      notifications: notifications

logging:
  level:
    root: INFO


